### ISSUE TITLE
ImportError: DLL Load Failed While Importing QtCore

### ISSUE THREAD

**Issue by y0himba** [rohankishore/Spotifyte#7]
Followed the install instructions, although my `main.py` is in the `/src` directory, so `CD /src` then `python -m main.py`.

`PS C:\Tools\Spotifyte\src> python -m main.py
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Tools\Spotifyte\src\main.py", line 6, in <module>
    from qfluentwidgets import (NavigationBar, NavigationItemPosition, MessageBox,
  File "C:\Python310\lib\site-packages\qfluentwidgets\__init__.py", line 17, in <module>
    from .components import *
  File "C:\Python310\lib\site-packages\qfluentwidgets\components\__init__.py", line 1, in <module>
    from .dialog_box import *
  File "C:\Python310\lib\site-packages\qfluentwidgets\components\dialog_box\__init__.py", line 1, in <module>
    from .color_dialog import ColorDialog
  File "C:\Python310\lib\site-packages\qfluentwidgets\components\dialog_box\color_dialog.py", line 2, in <module>
    from PySide6.QtCore import Qt, Signal, QPoint, QRegularExpression, QSize
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.`

Windows 11 fully updated, Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32

What can I do to help troubleshoot?  I am really eager to try this out.

**Comment by rohankishore** [comment]
Hey @y0himba 

This's a QT venv error and there's nothing wrong with the code. To solve this,
- Create a new virtual environment (do not import existing packages from the old env)
- Install all libraries freshly

This's a known issue in PyQt6/PySide6/PyQt5. As of now, they haven't released any fixes. Only creating new environments fix it. If you want help regarding creating environments,
- [Creation of Virtual Env (Src: Python)](https://docs.python.org/3/library/venv.html)
- [How to Set Up a Virtual Environment in Python (Src: FreeCodeCamp)](https://docs.python.org/3/library/venv.html)

Thanks
@rohankishore

**Comment by y0himba** [comment]
Thank you so much! Working now.
